/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      fontFamily: {
        sans: ['Roboto', 'system-ui', 'sans-serif'],
      },
      colors: {
        md: {
          primary: '#6750A4',
          'primary-container': '#EADDFF',
          'on-primary': '#FFFFFF',
          'on-primary-container': '#21005D',
          secondary: '#625B71',
          'secondary-container': '#E8DEF8',
          surface: '#FFFBFE',
          'surface-dim': '#F3EDF7',
          'surface-container': '#F3EDF7',
          'surface-container-high': '#ECE6F0',
          'surface-container-highest': '#E6E0E9',
          'on-surface': '#1C1B1F',
          'on-surface-variant': '#49454F',
          outline: '#79747E',
          'outline-variant': '#CAC4D0',
          error: '#B3261E',
          'error-container': '#F9DEDC',
        },
        'md-dark': {
          primary: '#D0BCFF',
          'primary-container': '#4F378B',
          'on-primary': '#371E73',
          'on-primary-container': '#EADDFF',
          secondary: '#CCC2DC',
          'secondary-container': '#4A4458',
          surface: '#1C1B1F',
          'surface-dim': '#141218',
          'surface-container': '#211F26',
          'surface-container-high': '#2B2930',
          'surface-container-highest': '#36343B',
          'on-surface': '#E6E1E5',
          'on-surface-variant': '#CAC4D0',
          outline: '#938F99',
          'outline-variant': '#49454F',
        },
      },
      boxShadow: {
        'md-1': '0 1px 2px rgba(0,0,0,0.08), 0 1px 3px rgba(0,0,0,0.06)',
        'md-2': '0 2px 6px rgba(0,0,0,0.10), 0 1px 2px rgba(0,0,0,0.06)',
        'md-3': '0 4px 12px rgba(0,0,0,0.12), 0 2px 4px rgba(0,0,0,0.08)',
        'md-fab': '0 6px 10px rgba(103,80,164,0.35), 0 2px 6px rgba(0,0,0,0.15)',
      },
      borderRadius: {
        'md-sm': '8px',
        'md-md': '12px',
        'md-lg': '16px',
        'md-xl': '28px',
      },
    },
  },
  plugins: [],
}
